# Generated by Django 2.1.7 on 2021-02-10 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ken', '0003_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Astroh',
        ),
    ]
