# Generated by Django 2.1.7 on 2021-02-10 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ken', '0004_auto_20210209_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='astroh',
            name='title',
        ),
    ]
