# Generated by Django 2.1.7 on 2021-02-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ken', '0007_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
