# Generated by Django 2.1.7 on 2021-02-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ken', '0008_auto_20210215_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='joinus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
